### ISSUE TITLE
Out dated Dependencies

### ISSUE THREAD

**Issue by mohdt786** [data-integrations/firestore-plugins#8]
I'm unable to perform the following:
`mvn clean install`
or
`mvn clean package`

Getting the following error:
`[ERROR] Failed to execute goal on project firestore-plugins: Could not resolve dependencies for project io.cdap.plugin:firestore-plugins:jar:1.1.0-SNAPSHOT: The following artifacts could not be resolved: io.cdap.plugin:format-common:jar:2.5.0-SNAPSHOT, io.cdap.plugin:format-avro:jar:2.5.0-SNAPSHOT, io.cdap.plugin:hydrator-common:jar:2.5.0-SNAPSHOT: Could not find artifact io.cdap.plugin:format-common:jar:2.5.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots)`

**Comment by albertshau** [comment]
bumped the dependency to 2.5.0
